### ISSUE TITLE
Question about future of this plugin

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [vinsworldcom/nppQCP#1]
Hi @vinsworldcom, any plans to work around this plugin? I have some bugs (related to color detection), and I don't know if it makes sense to open them if you don't have plans to work on this plugin.

**Comment by vinsworldcom** [comment]
@ArkadiuszMichalski not really.  I saw this was abandoned and the author said he wouldn't update and had moved to VSCode.  I thought it useful for editing N++ themes so added some logic for that, but otherwise it's not my code and the color picker part is from some other project.

Feel free to fork or submit pull requests but I probably won't be fixing any bugs myself .. like I said, I don't use this plugin anymore myself.

Cheers.

**Comment by ArkadiuszMichalski** [comment]
Ok, thx for fast answear.
