### ISSUE TITLE
enable for xml files

### ISSUE THREAD

**Issue by bmos** [vinsworldcom/nppQCP#2]
any chance this can be used with xml files?

**Comment by vinsworldcom** [comment]
I should be used in any files that have the hex color digits matching the pattern it looks for.

`#XXXXXX`

and 

Notepad++ theme XML files:

*gColor="XXXXXX"

What does your XML document look like?

Cheers.

**Comment by bmos** [comment]
![Capture](https://user-images.githubusercontent.com/1916835/108529592-9e3d0680-72a2-11eb-9e6d-ae7595bc7bad.PNG)

I put the "NppQCP.dll" file in "C:\Program Files\Notepad++\plugins"
I am using Notepad++ 64 bit, any chance it's 32-bit only?

**Comment by vinsworldcom** [comment]
There are [2 versions in the release](https://github.com/vinsworldcom/nppQCP/releases/tag/2.1.0.2); x86 = 32 bits, x64 = 64 bits - did you download and install the right one?

When you start Notepad++ with the wrong DLL version you'll get an error.

What version of Notepad++ are you using?  You cannot put a plugin DLL in the plugins/ folder after version 7.6 or so.  You need to put it in:

`C:\Program Files\Notepad++\plugins\NppQCP\NppQCP.dll`

I do not use this plugin anymore so a quick test shows its working for Notepad++ theme files:

![image](https://user-images.githubusercontent.com/9657169/108531931-43f17500-72a5-11eb-934f-2cc08b658b36.png)

but not for the other matching of `#XXXXXX`.  If you can figure it out, please submit a pull request, but I will not be looking at this since:

- it is not my plugin - I forked it to improve its use for my needs
- I do not use this plugin anymore.

Maybe try the original version of the plugin that I reference in the README?

Cheers.

**Comment by vinsworldcom** [comment]
Actually, it's original behavior does work - it's matching on a terminator of:

` ;.)\0`

So try putting a semicolon `;` after your 6-digit color and it should match.

Cheers.

**Comment by vinsworldcom** [comment]
Have a look at this [new release](https://github.com/vinsworldcom/nppQCP/releases/tag/2.1.1.1) and see if it fixes your issue.

Again, please install in a subdirectory of `plugins/NppQCP/NppQCP.dll`

Cheers.

**Comment by bmos** [comment]
it works!
I didn't have it in a folder. Thanks for clarifying that.
